=== kononir/LogisticsBase/src/main/resources/logistics_base_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/logistics_base"
        xmlns:tns="http://www.epam.com/logistics_base"
        elementFormDefault="qualified">
    <element name="base">
        <complexType>
            <sequence>
                <element ref="tns:freight-vans"/>
            </sequence>

            <attribute name="terminals-number" type="positiveInteger" use="required"/>
        </complexType>
    </element>

    <element name="freight-vans">
        <complexType>
            <sequence>
                <element name="freight-van" type="tns:FreightVan" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="FreightVan">
        <attribute name="state" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="loaded"/>
                    <enumeration value="unloaded"/>
                    <enumeration value="loaded_with_perishable_goods"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
</schema>

=== kononir/LogisticsBase/src/main/resources/base.xml
<?xml version="1.0" encoding="UTF-8" ?>
<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.epam.com/logistics_base"
      xsi:schemaLocation="http://www.epam.com/logistics_base logistics_base_schema.xsd"
      terminals-number="2">
    <freight-vans>
        <freight-van state="loaded"/>
        <freight-van state="loaded"/>
        <freight-van state="loaded"/>
        <freight-van state="loaded"/>
        <freight-van state="unloaded"/>
        <freight-van state="unloaded"/>
        <freight-van state="loaded_with_perishable_goods"/>
        <freight-van state="loaded_with_perishable_goods"/>
        <freight-van state="loaded_with_perishable_goods"/>
        <freight-van state="loaded_with_perishable_goods"/>
    </freight-vans>
</base>
